---
build_from:
  amd64: ghcr.io/hassio-addons/base/amd64:11.1.2
  aarch64: ghcr.io/hassio-addons/base/aarch64:11.1.2
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
args:
  SHARRY_VERSION: 1.9.0
